Homework2
made-ml-in-prod-2021/opl242-test pull request #3
Opened 2021-05-19 20:52 UTC by opl242-test

Self-evaluation печальный: Не сумел победить докер на винде

2021-05-23 13:39 UTC, Mikhail-M requested changes
Приведите структуру в порядок и в реквесте не должно быть кода первой дз
пример
https://github.com/made-ml-in-prod-2021/kernela

2021-06-11 02:16 UTC, opl242-test commented
Поправил структуру, всё доделал. Весь код, касающийся второго ДЗ, теперьтолько в папке online_inference

2021-06-11 02:37 UTC, opl242-test commented
Self-evaluation:

+1) Оберните inference вашей модели в rest сервис(вы можете использовать как FastAPI, так и flask, другие желательно не использовать, дабы не плодить излишнего разнообразия для проверяющих), должен быть endpoint /predict (3 балла)

+2) Напишите тест для /predict  (3 балла) (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/)

+3) Напишите скрипт, который будет делать запросы к вашему сервису -- 2 балла

+4) Сделайте валидацию входных данных (например, порядок колонок не совпадает с трейном, типы не те и пр, в рамках вашей фантазии)  (вы можете сохранить вместе с моделью доп информацию, о структуре входных данных, если это нужно) -- 3 доп балла
https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена

+* 5) Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run), внутри контейнера должен запускать сервис, написанный в предущем пункте, закоммитьте его, напишите в readme корректную команду сборки (4 балл)

+* 6) Оптимизируйте размер docker image (3 доп балла) (опишите в readme.md что вы предприняли для сокращения размера и каких результатов удалось добиться)  -- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

+* 7) опубликуйте образ в https://hub.docker.com/, используя docker push (вам потребуется зарегистрироваться) (2 балла)

+* 8) напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл)
Убедитесь, что вы можете протыкать его скриптом из пункта 3

+* 9) проведите самооценку -- 1 доп балл

+* - сделанные после soft-deadline
Итого: 11 + 11*0.6 = 17.6

2021-06-12 15:49 UTC, Mikhail-M approved these changes
Оптимизация: 1.5 балла
Валидация: 1.5 балла

Итого, баллов 15

Баллы: 15

2021-06-12 19:27 UTC, merged